### ISSUE TITLE
Add supporting mf2 docs

### ISSUE THREAD

**Issue by willnorris** [pfefferle/dash-microformats2#1]
Oh my goodness, I love this repo! :+1: 

What do you think about including all http://microformats.org/wiki/microformats2-* docs?  Mainly, I'm interested in the parsing docs, since that's what I'm spending a lot of time on right now.  Or are you wanting to focus more on just the specs that content authors would reference?

**Comment by pfefferle** [comment]
Thanks :)

Sure, good idea!

Why do you think about changing the `type` for the specs to `object`? So we have guides (microformats2 and microformats2-_) and objects (h-_)?

**Comment by willnorris** [comment]
that sounds about right

**Comment by pfefferle** [comment]
Added guides, except issues and brainstorming pages, because I think they change too often...
